Centro_Medico/Centro_Medico/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ingresoUsers/', include('ingresoUsers.urls')),
    path('', include('centroWeb.urls')),
]

Centro_Medico/centroWeb/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index, name='index'),
    path('creaCuenta/', views.UsersPost, name='formulario')
]

Centro_Medico/ingresoUsers/urls.py
from django.urls import path
from .import views

urlpatterns =[
    path('',views.listaUsers, name='listaUsers'),
    path('registro/',views.ingresoUser, name='ingresoUser'),
    path('eliminar/<str:pk>/',views.eliminarUser, name='eliminarUser'),
]

Centro_Medico/centroWeb/models.py
from django.db import models

# Create your models here.

Centro_Medico/ingresoUsers/models.py
from django.db import models

# Create your models here.
class Users(models.Model):
    nombre = models.CharField(max_length=100, default='DEFAULT VALUE')
    apellido = models.CharField(max_length=100, default='DEFAULT VALUE')
    email = models.CharField(max_length=100, default='DEFAULT VALUE')
    tipoUsuario = models.CharField(max_length=60, default='DEFAULT VALUE')
    password = models.CharField(max_length=100, default='DEFAULT VALUE')

    class Meta:
        db_table = 'users'

    def __str__(self):
        return self.nombre
    
    
class tipoUsuario(models.Model):
    tipo = models.CharField(max_length=100, default='DEFAULT VALUE')

    class Meta:
        db_table = 'tipoUsuario'

    def __str__(self):
        return self.tipo

Centro_Medico/centroWeb/forms.py
from django import forms


class userForm(forms.Form):
    nombre = forms.CharField(max_length=100)
    apellido = forms.CharField(max_length=100)
    email = forms.CharField(max_length=100)
    tipoUsuario = forms.CharField(max_length=60)
    password = forms.CharField(max_length=100)

Centro_Medico/centroWeb/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from rest_framework.utils import json
from .forms import userForm
from django.shortcuts import render


# Create your views here.


def index(request):
    response = request.get('http://127.0.0.1:8000/ingresoUsers/').json()
    return render(request, 'web/index.html', {
        'response': response
    })


def UsersPost(request):
    url = "http://127.0.0.1:8000/ingresoUsers/registro"
    form = userForm(request.POST or None)
    if form.is_valid():
        nombre = form.cleaned_data.get("nombre")
        apellido = form.cleaned_data.get("apellido")
        email = form.cleaned_data.get("email")
        tipoUsuario = form.cleaned_data.get("tipoUsuario")
        password = form.cleaned_data.get("password")
        data = {'nombre': nombre, 'apellido': apellido, 'email': email, 'tipoUsuario': tipoUsuario, 'password': password}
        headers = {'Content-type': 'application/json', }
        response = request.post(url, data=json.dumps(data), headers=headers)
        return render(request, 'web/form.html', {
            'response': response
        })

Centro_Medico/ingresoUsers/views.py
from django.views import View
from .models import Users
from rest_framework.decorators import api_view
from .serializers import UserSerializer
from rest_framework.response import Response


# vista basada en la clase 
# metodo para listar los usuarios //para probar si sirve
@api_view(['GET'])
def listaUsers(request):
    usuarios = Users.objects.all()
    serializer = UserSerializer(usuarios, many=True)
    return Response(serializer.data)

# metodo para agregar usuarios
@api_view(['POST'])  
def ingresoUser(request):
    serializer = UserSerializer(data=request.data)
    if serializer.is_valid():
        serializer.save()
    else:
        return Response(serializer.errors)
    return Response(serializer.data)
    
# metodo para eliminar usuarios
@api_view(['DELETE'])
def eliminarUser(request, pk):
    usuarios = Users.objects.get(id=pk)
    usuarios.delete()
    return Response('Usuario eliminado')

Centro_Medico/centroWeb/templates/web/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Formulario enviado</title>
</head>
<body>
    <Formulario>Formulario Enviado</Formulario>
</body>
</html>

Centro_Medico/centroWeb/templates/web/index.html
<ul>
    {% for obj in response %}
        <li>{{ obj.id }} - {{ obj.nombre }}</li>
    {% endfor %}
    </ul>
    <form action="{% url 'web:formulario' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <p><label for="id_nombre">Nombre:</label>
        <input id="id_nombre" type="text" name="nombre" maxlength="100" required></p>
    <p><label for="id_apellido">Apellido:</label>
        <input id="id_apellido" type="text" name="apellido" maxlength="100" required></p>
    <p><label for="id_email">Email:</label>
        <input id="id_email" type="email" name="email" maxlength="100" required></p>
    <p><label for="id_password">Contraseña:</label>
        <input id="id_password" type="password" name="password" maxlength="100" required></p>
    <p><label for="id_tipoUsuario">Tipo usuario:</label>
        <input id="id_tipoUsuario" type="text" name="stock" maxlength="25" required></p>
        <button type="submit">Crear productos</button>
    </form>